#!/usr/bin/env bash
# 0. World wide web
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)
# Add the subdomain www to your domain, point it to your lb-01
# Add the subdomain lb-01 to your domain, point it to your lb-01 IP
# Add the subdomain web-01 to your domain, point it to your web-01 IP
# Add the subdomain web-02 to your domain, point it to your web-02 IP
# Your Bash script must accept 2 arguments domain & subdomain
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
# When only the parameter domain is provided, display information for its subdomains www, lb-01, web-01 and web-02
# When passing domain and subdomain parameters, display information for the specified subdomain
if [ "$#" -eq 1 ];
# si nos pasan solo un comando tenemos que correr dig para todas las salidas y printiar con el formato solicitado.
then
	subdomain=("www" "lb-01" "web-01" "web-02")
	for i in "${subdomain[@]}"
	do
# combino cada subdomio con el dominio que viene por parametro
# luego voy a la sección answe section con el Grep
# luego ya dentro del AWK identifico las variables que necesito en el print
# luego printeo
	dig "$i"."$1"| grep -A1 'ANSWER SECTION:' | awk 'NR==2{SUB=$1; RECORDTYPE=$4; DESTINATION=$5; split(SUB, subx, "."); print "The subdomain " subx[1], "is a " RECORDTYPE, "record and points to " DESTINATION}';
	done
elif [ "$#" -eq 2 ];
then
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2{SUB=$1; RECORDTYPE=$4; DESTINATION=$5; split(SUB, subx, "."); print "The subdomain " subx[1], "is a " RECORDTYPE, "record and points to " DESTINATION}';
fi
