#!/usr/bin/env bash
# https://www.hostinger.es/tutoriales/comando-scp
# scp [other options] [source username@IP]:/[directory and file name] 
# [destination username@IP]:/[destination directory]
# https://blog.katastros.com/a?ID=01100-4d89d67a-c19d-4038-9788-1158bc397d52

if [ "$#" -lt 4 ]
    then echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
