#!/usr/bin/env bash
# Script that install nginx
# https://www.youtube.com/watch?v=
# _LQv96MdtCk&list=PLqRCtm0kbeHD7A5f8Yft-5qFg-sgXvGzR

sudo apt update
sudo apt-get -y install nginx 
cd /var/www/html || exit
sudo chmod 777 index.nginx-debian.html
echo Hello World! > index.nginx-debian.html
sudo service nginx restart
