#!/usr/bin/env bash
# configure web-02 to be identical to web-01:
# Install nginx web server
# Replace a line with multiple lines with sed
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# NEW: The name of the custom HTTP header must be X-Served-By
# NEW:The value of the custom HTTP header must be the hostname of the server Nginx is running on


sudo apt update
sudo apt -y install nginx
cd /var/www/html || exit
sudo chmod 777 index.nginx-debian.html
echo Hello World! > index.nginx-debian.html
# Make a copy just in case of default file before sed in that
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/Backdefault
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Make a copy just in case of default file before sed in that
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/2Backdefault
# New command start
sudo sed -i "/listen 80 default_server/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-enabled/default
# New command finish
sudo touch /var/www/html/404-page.html
sudo chmod 777 /var/www/html/404-page.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404-page.html
sudo service nginx restart
