#!/usr/bin/env bash
# MySQL backup
# mysqldump -u root -p"$1" --all-databases > backup.sql
# tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
sudo mysqldump -uroot -p"$1" --all-databases | sudo tee backup.sql
tar -cvzf "$(date '+%d-%m-%Y').tar.gz" backup.sql
