#!/usr/bin/env bash
# Block all incoming traffic but
sudo apt update -y
sudo apt install ufw -y
sudo sed -i "s/IPV6=no/IPV6=yes/g" /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
